export const categories = [
  { CategoryId: 1, CategoryName: "Món chính", IsActive: true },
  { CategoryId: 2, CategoryName: "Ăn vặt", IsActive: true },
  { CategoryId: 3, CategoryName: "Đồ uống", IsActive: true },
];
export const products = [
  {
    ProductId: 1,
    CategoryId: 1,
    ProductName: "Mì xào bò",
    Price: 28000,
    Stock: 24,
    IsActive: true,
  },
  {
    ProductId: 2,
    CategoryId: 1,
    ProductName: "Cơm gà xối mỡ",
    Price: 35000,
    Stock: 18,
    IsActive: true,
  },
  {
    ProductId: 3,
    CategoryId: 3,
    ProductName: "Trà đào cam sả",
    Price: 15000,
    Stock: 32,
    IsActive: true,
  },
  {
    ProductId: 4,
    CategoryId: 2,
    ProductName: "Khoai tây chiên",
    Price: 20000,
    Stock: 16,
    IsActive: true,
  },
  {
    ProductId: 5,
    CategoryId: 1,
    ProductName: "Mì trộn trứng xúc xích",
    Price: 25000,
    Stock: 20,
    IsActive: true,
  },
  {
    ProductId: 6,
    CategoryId: 3,
    ProductName: "Cà phê sữa đá",
    Price: 18000,
    Stock: 35,
    IsActive: true,
  },
  {
    ProductId: 7,
    CategoryId: 3,
    ProductName: "Coca-Cola",
    Price: 12000,
    Stock: 5,
    IsActive: true,
  },
  {
    ProductId: 8,
    CategoryId: 2,
    ProductName: "Xúc xích chiên",
    Price: 15000,
    Stock: 8,
    IsActive: true,
  },
  {
    ProductId: 9,
    CategoryId: 3,
    ProductName: "Nước suối",
    Price: 8000,
    Stock: 48,
    IsActive: true,
  },
  {
    ProductId: 10,
    CategoryId: 1,
    ProductName: "Burger bò phô mai",
    Price: 38000,
    Stock: 0,
    IsActive: true,
  },
  {
    ProductId: 11,
    CategoryId: 2,
    ProductName: "Gà viên chiên",
    Price: 25000,
    Stock: 12,
    IsActive: false,
  },
  {
    ProductId: 12,
    CategoryId: 3,
    ProductName: "Nước tăng lực",
    Price: 15000,
    Stock: 22,
    IsActive: true,
  },
];
// Display metadata is separate from the Products table.
export const productVisuals = {
  1: ["🍜", "Bò mềm, rau xanh, mì xào nóng hổi"],
  2: ["🍗", "Gà giòn rụm, cơm nóng, thêm năng lượng"],
  3: ["🍑", "Thanh mát, thơm đào và sả tươi"],
  4: ["🍟", "Giòn bên ngoài, mềm bên trong"],
  5: ["🍝", "Mì đậm vị, trứng và xúc xích"],
  6: ["☕", "Cà phê đậm đà, sữa ngọt dịu"],
  7: ["🥤", "Mát lạnh, sảng khoái tức thì"],
  8: ["🌭", "Nóng giòn, ăn nhẹ giữa trận"],
  9: ["💧", "Bổ sung nước cho trận đấu dài"],
  10: ["🍔", "Bò nướng và phô mai béo ngậy"],
  11: ["🍿", "Gà viên giòn, thêm chút sốt cay"],
  12: ["⚡", "Nạp năng lượng, tiếp cuộc chơi"],
};
export const mockData = products;
