import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowUpRight, CheckCircle2, ChevronRight, Clock3, Cpu, Gamepad2, History, Info, Monitor, Plus, ReceiptText, Trophy, Users, Utensils, WalletCards, Zap } from 'lucide-react';
import HomeDialog from './HomeDialog';
import { useHomeData } from './useHomeData';
import { CURRENT_CUSTOMER_ID } from './mockData';
import { dateTime, depositDemo, duration, getActivities, getHomeSummary, money, statusLabels } from './homeModel';
import './home.css';

const foodArt = { 1: '🍜', 2: '🍗', 3: '🍑', 4: '☕', 5: '🍟', 6: '🥤' };
const activityIcons = { order: Utensils, wallet: WalletCards, invoice: ReceiptText };
function Badge({ status }) { return <span className={`home-badge ${['Pending', 'Preparing', 'Unpaid'].includes(status) ? 'amber' : status === 'Cancelled' ? 'muted' : ''}`}><i/>{statusLabels[status] || status}</span>; }
function FoodArt({ product }) { return <div className={`home-food-art food-art-${product.CategoryId}`} aria-hidden="true"><span>{foodArt[product.ProductId] || '🍽️'}</span><i/><b>TRAM KITCHEN</b></div>; }
function Empty({ children }) { return <div className="home-empty"><Info size={24}/><p>{children}</p></div>; }

export default function HomePage() {
  const navigate = useNavigate();
  const { db, warning, commit, reset } = useHomeData();
  const [now, setNow] = useState(() => new Date());
  const [modal, setModal] = useState(null);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [filter, setFilter] = useState('all');
  const [showAll, setShowAll] = useState(false);
  const [amount, setAmount] = useState('100000');
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(timer); }, []);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 6000); return () => clearTimeout(timer); }, [notice]);
  const summary = getHomeSummary(db, now);
  const { customer, session, computer, room, type, products, tournament } = summary;
  const activities = useMemo(() => getActivities(db), [db]);
  const filteredActivities = activities.filter((row) => filter === 'all' || row.kind === filter);
  const visibleActivities = showAll ? filteredActivities : filteredActivities.slice(0, 5);
  const game = db.Games.find((row) => row.GameId === tournament?.GameId);
  const registered = db.TournamentRegistrations.find((row) => row.TournamentId === tournament?.TournamentId && row.CustomerId === CURRENT_CUSTOMER_ID && row.Status !== 'Cancelled');
  const canOrder = !!session && computer?.Status === 'Occupied' && customer?.Status === 'Active';
  const featured = [...products].sort((a, b) => Number(b.Stock > 0) - Number(a.Stock > 0)).slice(0, 3);
  const selectedActivity = activities.find((row) => row.key === modal?.key);
  function open(kind, extra = {}) { setError(''); setModal({ kind, ...extra }); }
  function close() { setError(''); setModal(null); }
  function run(action, message) { try { action(); setError(''); setNotice(message); return true; } catch (err) { setError(err.message); return false; } }
  function goToOrdering(product) {
    navigate('/client/ordering', {
      state: {
        openCart: Boolean(product),
        initialCartItems: product ? [{ ProductId: product.ProductId, ProductName: product.ProductName, Quantity: 1 }] : [],
      },
    });
  }
  const firstName = customer?.FullName.split(' ').slice(-2).join(' ') || 'bạn';

  return <div className="cafe-home">
    <div className="home-demo-strip"><span><Info size={14}/> Bản trải nghiệm · Dữ liệu mẫu lưu trên trình duyệt</span><button onClick={() => open('reset')}>Khôi phục bản mẫu</button></div>
    {warning && <div className="home-alert" role="alert">{warning}</div>}
    <div className="home-heading"><div><div className="home-eyebrow">PLAY. CONNECT. REPEAT.</div><h1>Chào {firstName}, sẵn sàng vào trận<span>?</span></h1><p>Mọi thứ bạn cần cho buổi chơi hôm nay, ngay tại đây.</p></div><button className="home-button" onClick={() => goToOrdering()}><Utensils size={16}/> Gọi món tại máy</button></div>
    <div className="home-dashboard-grid">
      <section className="home-panel home-session" aria-labelledby="session-title">
        <div className="home-session-content"><div className="home-card-top"><h2 id="session-title"><Monitor size={19}/>{computer?.ComputerName || 'Phiên chơi của bạn'}</h2><Badge status={session ? 'Active' : 'Idle'}/></div>
          {session ? <><div className="home-eyebrow home-timer-label">THỜI GIAN ĐÃ CHƠI</div><div className="home-timer" aria-label="Thời gian đã chơi">{duration(summary.elapsed)}</div><p className="home-start"><Clock3 size={13}/> Bắt đầu {dateTime(session.StartTime)}</p><div className="home-machine-meta"><span>{room?.RoomName || 'Chưa có thông tin phòng'} · Tầng {room?.Floor ?? '—'} · {type?.TypeName}</span><span><Cpu size={13}/>{type?.CPU} · RAM {type?.RAM} · {type?.GPU}</span></div></> : <Empty>Bạn chưa có phiên chơi đang hoạt động. Liên hệ quầy để bắt đầu.</Empty>}
        </div>
        <div className="home-rig" aria-hidden="true"><div className="home-rig-orbit"/><div className="home-rig-screen"><Gamepad2 size={60} strokeWidth={1}/><span>READY TO PLAY</span><div className="home-rig-line"/></div><div className="home-rig-stand"/><div className="home-rig-keyboard"/></div>
        <div className="home-session-footer"><span>Đơn giá <strong>{money(type?.PricePerHour)}<small> / giờ</small></strong></span><span>Tiền máy tạm tính <strong>{money(summary.sessionCost)}</strong></span><button onClick={() => open('session')}>Chi tiết phiên <ChevronRight size={14}/></button></div>
      </section>
      <section className="home-panel home-wallet" aria-labelledby="wallet-title"><div className="home-card-top"><h2 id="wallet-title">Ví của bạn</h2><WalletCards size={20}/></div><span className="home-muted">Số dư hiện tại</span><div className="home-balance">{money(customer?.WalletBalance)}</div><button className="home-button primary" onClick={() => open('deposit')}><Plus size={16}/> Nạp tiền vào ví</button><div className="home-balance-row"><span>Gọi món · chưa thanh toán</span><strong>{money(summary.unpaidOrders)}</strong></div><div className="home-balance-row"><span>Tổng phiên này · tạm tính</span><strong>{money(summary.total)}</strong></div>{summary.remainingHours !== null && <div className={`home-remaining ${summary.remainingHours < 1 ? 'low' : ''}`}><Clock3 size={13}/>{summary.remainingHours > 0 ? `Dự kiến còn ${Math.floor(summary.remainingHours)} giờ ${Math.floor(summary.remainingHours * 60) % 60} phút` : 'Số dư dự kiến không đủ cho chi phí phiên này'}<span title="Ước tính sau khi trừ toàn bộ tiền máy và đơn món chưa thanh toán; chưa trừ tiền thật."><Info size={13}/></span></div>}</section>
      <section className="home-food-section" aria-labelledby="food-title"><div className="home-section-heading"><div><span className="home-eyebrow">TRAM KITCHEN</span><h2 id="food-title">Nạp năng lượng, tiếp trận</h2></div><button className="home-text-button" onClick={() => goToOrdering()}>Xem thực đơn <ArrowUpRight size={15}/></button></div><div className="home-food-grid">{featured.map((product) => <article className="home-food-card" key={product.ProductId}><FoodArt product={product}/><div className="home-food-body"><span className="home-food-category">{db.Categories.find((c) => c.CategoryId === product.CategoryId)?.CategoryName}</span><h3>{product.ProductName}</h3><div className="home-food-bottom"><strong>{money(product.Price)}</strong><button className="home-add" disabled={!canOrder || product.Stock === 0} aria-label={`Thêm ${product.ProductName} vào giỏ`} onClick={() => goToOrdering(product)}><Plus size={18}/></button></div></div></article>)}</div>{featured.length === 0 && <Empty>Thực đơn đang được cập nhật.</Empty>}</section>
      <section className="home-panel home-tournament" aria-labelledby="tournament-title"><Trophy className="home-trophy-art" size={145} strokeWidth={.7} aria-hidden="true"/><div className="home-tournament-content"><span className="home-badge"><i/>{registered ? 'BẠN ĐÃ ĐĂNG KÝ' : 'GIẢI ĐẤU SẮP TỚI'}</span><h2 id="tournament-title">{tournament?.TournamentName || 'Hẹn bạn ở giải đấu tới'}</h2>{tournament ? <><p><Gamepad2 size={15}/>{game?.GameName} <span>·</span><Users size={15}/> Đội {game?.TeamSize} người</p><p><Clock3 size={15}/>{dateTime(tournament.StartTime)}</p><div className="home-tournament-fee">{tournament.EntryFee === 0 ? 'Miễn phí tham gia' : money(tournament.EntryFee)}<span> / người chơi</span></div><button className="home-button tournament" onClick={() => navigate(`/client/tournaments?tournament=${tournament.TournamentId}`)}>{registered ? 'Xem đăng ký của bạn' : 'Chi tiết & đăng ký'}<ArrowUpRight size={16}/></button></> : <p>Giải đấu mới sẽ xuất hiện tại đây khi lịch được công bố.</p>}</div></section>
    </div>
    <section className="home-activity-section" aria-labelledby="activity-title"><div className="home-section-heading"><div><span className="home-eyebrow">MỌI THỨ TRONG TẦM TAY</span><h2 id="activity-title">Hoạt động gần đây</h2></div><button className="home-text-button" onClick={() => setShowAll(!showAll)}>{showAll ? 'Thu gọn' : 'Xem tất cả'}<History size={15}/></button></div><div className="home-panel"><div className="home-tabs" role="group" aria-label="Lọc hoạt động">{[['all', 'Tất cả'], ['order', 'Đơn món'], ['wallet', 'Giao dịch ví'], ['invoice', 'Hóa đơn']].map(([value, label]) => <button key={value} aria-pressed={filter === value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)}>{label}{value === 'all' && <span>{activities.length}</span>}</button>)}</div><div className="home-table-wrap"><table className="home-table"><thead><tr><th>Giao dịch / đơn hàng</th><th>Thời gian</th><th>Số tiền</th><th>Trạng thái</th><th><span className="home-sr-only">Chi tiết</span></th></tr></thead><tbody>{visibleActivities.map((row) => { const Icon = activityIcons[row.kind]; return <tr key={row.key}><td><div className="home-activity-name"><span className={`home-activity-icon ${row.kind}`}><Icon size={18}/></span><div><button onClick={() => open('activity', { key: row.key })}>{row.title}</button><small>{row.subtitle}</small></div></div></td><td className="home-date">{dateTime(row.time)}</td><td className={`home-amount ${row.kind === 'wallet' && row.amount > 0 ? 'positive' : ''}`}>{row.kind === 'wallet' && row.amount > 0 ? '+' : ''}{money(row.amount)}</td><td><Badge status={row.status}/></td><td><button className="home-icon-button" aria-label={`Xem ${row.title}`} onClick={() => open('activity', { key: row.key })}><ChevronRight size={17}/></button></td></tr>; })}</tbody></table></div>{visibleActivities.length === 0 && <Empty>Chưa có hoạt động trong mục này.</Empty>}</div></section>
    <footer className="home-footer"><span><Zap size={13}/> TRAM · Chơi hết mình, kết nối hết cỡ.</span><time dateTime={now.toISOString()}>{dateTime(now)}</time></footer>
    {notice && <div className="home-toast" role="status"><CheckCircle2 size={20}/>{notice}</div>}

    {modal && <HomeDialog title={{ deposit: 'Nạp tiền vào ví', activity: selectedActivity?.title || 'Chi tiết hoạt động', session: 'Chi tiết phiên chơi', reset: 'Khôi phục dữ liệu mẫu' }[modal.kind]} onClose={close}>
      {error && <div className="home-alert" role="alert">{error}</div>}
      {modal.kind === 'deposit' && <form onSubmit={(event) => { event.preventDefault(); if (run(() => commit((data) => depositDemo(data, Number(amount))), 'Đã nạp tiền mô phỏng vào ví. Không có giao dịch thật.')) close(); }}><div className="home-info-box"><Info size={18}/><span>Đây là thao tác mô phỏng để kiểm thử giao diện. Không chuyển tiền thật. Khi sử dụng tại quán, liên hệ nhân viên để nạp tiền.</span></div><div className="home-detail-row"><span>Số dư hiện tại</span><strong>{money(customer?.WalletBalance)}</strong></div><label className="home-field">Số tiền muốn nạp (VNĐ)<input type="number" min="10000" max="2000000" step="1000" required value={amount} onChange={(event) => setAmount(event.target.value)}/></label><div className="home-preset-grid">{[50000, 100000, 200000, 500000].map((value) => <button type="button" key={value} aria-pressed={Number(amount) === value} className={Number(amount) === value ? 'selected' : ''} onClick={() => setAmount(String(value))}>{money(value)}</button>)}</div><p className="home-fine-print">Từ 10.000đ đến 2.000.000đ, theo bội số 1.000đ.</p><button className="home-button primary" disabled={customer?.Status !== 'Active'} type="submit"><WalletCards size={16}/> Xác nhận nạp mô phỏng</button></form>}
      {modal.kind === 'session' && <><div className="home-info-box"><Monitor size={24}/><span>{computer?.ComputerName || 'Chưa có phiên chơi'}<br/>{room?.RoomName} {session && `· Phiên #${session.SessionId}`}</span></div>{session && <><div className="home-detail-row"><span>Thời gian sử dụng</span><strong>{duration(summary.elapsed)}</strong></div><div className="home-detail-row"><span>Đơn giá hiện tại</span><strong>{money(type?.PricePerHour)} / giờ</strong></div><div className="home-detail-row"><span>Tiền máy đã ghi nhận</span><strong>{money(session.TotalCost)}</strong></div><div className="home-detail-row"><span>Lần ghi nhận gần nhất</span><strong>{dateTime(session.LastChargedAt || session.StartTime)}</strong></div>{db.SessionCharges.filter((c) => c.SessionId === session.SessionId).map((charge) => <div className="home-charge" key={charge.ChargeId}><span>{dateTime(charge.StartTime)} → {dateTime(charge.EndTime)}</span><strong>{money(charge.Amount)}</strong></div>)}<div className="home-detail-row"><span>Tiền máy tạm tính hiện tại</span><strong>{money(summary.sessionCost)}</strong></div><div className="home-detail-row"><span>Đơn món (không gồm đơn hủy)</span><strong>{money(summary.orderTotal)}</strong></div><div className="home-cart-total"><span>Tổng phiên tạm tính</span><strong>{money(summary.total)}</strong></div><p className="home-fine-print">Tiền máy tạm tính = tiền đã ghi nhận + thời gian từ lần ghi nhận cuối × đơn giá. Bản mô phỏng chưa trừ tiền ví; hóa đơn cuối cùng do hệ thống tại quầy xác nhận.</p></>}</>}
      {modal.kind === 'activity' && selectedActivity && <><div className="home-detail-row"><span>{dateTime(selectedActivity.time)}</span><Badge status={selectedActivity.status}/></div>{selectedActivity.kind === 'order' && <><p className="home-dialog-intro">Phiên #{selectedActivity.record.SessionId} · {selectedActivity.record.InvoiceId ? `Hóa đơn #HD${selectedActivity.record.InvoiceId}` : 'Chưa lập hóa đơn'}</p>{db.OrderDetails.filter((d) => d.OrderId === selectedActivity.id).map((detail) => <div className="home-detail-row" key={detail.OrderDetailId}><span>{detail.Quantity} × {db.Products.find((p) => p.ProductId === detail.ProductId)?.ProductName || 'Sản phẩm đã ngừng bán'}<small>{money(detail.UnitPrice)} / phần</small></span><strong>{money(detail.Quantity * detail.UnitPrice)}</strong></div>)}<h3 className="home-small-heading">Tiến trình đơn</h3>{db.OrderStatusHistory.filter((h) => h.OrderId === selectedActivity.id).sort((a, b) => new Date(a.ChangedAt) - new Date(b.ChangedAt)).map((h) => <div className="home-detail-row" key={h.HistoryId}><span>{statusLabels[h.NewStatus] || h.NewStatus}</span><small>{dateTime(h.ChangedAt)}</small></div>)}</>}{selectedActivity.kind === 'wallet' && <><p className="home-dialog-intro">{selectedActivity.record.Description}</p><div className="home-detail-row"><span>Mã giao dịch</span><strong>#{selectedActivity.id}</strong></div><div className="home-detail-row"><span>Số dư sau giao dịch</span><strong>{money(selectedActivity.record.BalanceAfter)}</strong></div></>}{selectedActivity.kind === 'invoice' && <>{db.InvoiceDetails.filter((d) => d.InvoiceId === selectedActivity.id).map((d) => <div className="home-detail-row" key={d.InvoiceDetailId}><span>{d.Quantity} × {d.Description}</span><strong>{money(d.Amount)}</strong></div>)}<div className="home-detail-row"><span>Tạm tính</span><strong>{money(selectedActivity.record.Subtotal)}</strong></div><div className="home-detail-row"><span>Giảm giá</span><strong>−{money(selectedActivity.record.Discount)}</strong></div>{db.Payments.filter((p) => p.InvoiceId === selectedActivity.id).map((p) => <div className="home-detail-row" key={p.PaymentId}><span>{{ Cash: 'Tiền mặt', Wallet: 'Ví', Banking: 'Chuyển khoản' }[p.Method] || p.Method}<small>{statusLabels[p.Status] || p.Status} · {dateTime(p.PaymentTime)}</small></span><strong>{money(p.Amount)}</strong></div>)}</>}<div className="home-cart-total"><span>{selectedActivity.kind === 'wallet' ? 'Số tiền giao dịch' : 'Tổng cộng'}</span><strong>{money(selectedActivity.amount)}</strong></div></>}
      {modal.kind === 'reset' && <><p className="home-dialog-intro">Xóa các đơn món, lần nạp ví và đăng ký bạn đã thử trong bản mẫu của trang chủ này, rồi bắt đầu lại với dữ liệu ban đầu.</p><div className="home-dialog-actions"><button className="home-button" onClick={close}>Giữ dữ liệu</button><button className="home-button primary" onClick={() => { if (run(reset, 'Đã khôi phục dữ liệu mẫu.')) { close(); } }}>Khôi phục bản mẫu</button></div></>}
    </HomeDialog>}
  </div>;
}
