// CyberNet: giao diện demo, chưa kết nối API.

(()=>{const root=document.getElementById('cybernet'),content=root.querySelector('#cn-content'),feedback=root.querySelector('#cn-feedback');
const money=n=>n.toLocaleString('vi-VN')+' đ';const machines=Array.from({length:12},(_,i)=>({id:'PC-'+String(i+1).padStart(2,'0'),zone:i<8?'Thường':'VIP',state:[0,2,3,5,8,9,11].includes(i)?'busy':i===6?'repair':'free',name:['Minh Anh','Khách lẻ','Hoàng Nam','Gia Huy'][i%4],minutes:60+i*7,service:i===0?15000:0}));let selected=0,filter='all',zone='all',query='',page='machines';const bills=[];
const storageKey='cybernet-ui-demo-v1';
try { const saved=JSON.parse(localStorage.getItem(storageKey)||'null');
  if(saved && Array.isArray(saved.machines) && saved.machines.length===12 && Array.isArray(saved.bills)) {
    saved.machines.forEach((item,i)=>{if(['busy','free','repair'].includes(item.state) && Number.isFinite(item.minutes) && Number.isFinite(item.service)){machines[i].state=item.state;if(['Khách lẻ','Minh Anh','Hoàng Nam','Gia Huy'].includes(item.name))machines[i].name=item.name;machines[i].minutes=Math.max(0,item.minutes);machines[i].service=Math.max(0,item.service);}});
    saved.bills.filter(b=>typeof b.id==='string' && Number.isFinite(b.hours) && Number.isFinite(b.service)).forEach(b=>bills.push(b));
  }
} catch { /* Browsers may block storage for file://. The UI still works in memory. */ }
function saveDemo(){try{localStorage.setItem(storageKey,JSON.stringify({machines,bills}));}catch{}}
const safeText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={busy:'Đang sử dụng',free:'Sẵn sàng',repair:'Bảo trì'};const price=m=>m.zone==='VIP'?15000:10000;const cost=m=>Math.round(m.minutes/60*price(m));const badge=m=>'<span class="cn-badge '+m.state+'">'+labels[m.state]+'</span>';const icons=()=>{root.querySelectorAll('[data-lucide]').forEach(el=>{el.textContent=el.dataset.lucide==='monitor'?'▣':'▤';el.classList.add('cn-icon');el.removeAttribute('data-lucide')})};
const table=(heads,rows)=>'<div class="cn-table-wrap"><table><thead><tr>'+heads.map(h=>'<th scope="col">'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+safeText(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
function render(){feedback.textContent='';if(page==='machines'){content.innerHTML='<div class="cn-stats"><div class="cn-stat"><span class="cn-sub">Đang sử dụng</span><strong>'+machines.filter(m=>m.state==='busy').length+' / 12</strong></div><div class="cn-stat"><span class="cn-sub">Máy sẵn sàng</span><strong>'+machines.filter(m=>m.state==='free').length+'</strong></div><div class="cn-stat"><span class="cn-sub">Đang bảo trì</span><strong>'+machines.filter(m=>m.state==='repair').length+'</strong></div></div><div class="cn-toolbar"><input id="cn-search" aria-label="Tìm máy" placeholder="Tìm mã máy…"><select id="cn-filter" aria-label="Trạng thái máy"><option value="all">Tất cả trạng thái</option><option value="busy">Đang sử dụng</option><option value="free">Sẵn sàng</option><option value="repair">Bảo trì</option></select><select id="cn-zone" aria-label="Khu vực"><option value="all">Tất cả khu vực</option><option>Thường</option><option>VIP</option></select></div><div class="cn-room"><div id="cn-grid" class="cn-machines"></div><section id="cn-detail" class="cn-detail" aria-label="Chi tiết máy"></section></div>';root.querySelector('#cn-search').value=query;root.querySelector('#cn-filter').value=filter;root.querySelector('#cn-zone').value=zone;root.querySelector('#cn-search').oninput=e=>{query=e.target.value;grid()};root.querySelector('#cn-filter').onchange=e=>{filter=e.target.value;grid()};root.querySelector('#cn-zone').onchange=e=>{zone=e.target.value;grid()};grid();detail();}
else if(page==='combos'){renderCombos();}
else if(page==='sessions')content.innerHTML=table(['Máy','Khách hàng','Thời gian','Đơn giá / giờ','Tiền giờ'],machines.filter(m=>m.state==='busy').map(m=>[m.id,m.name,m.minutes+' phút',money(price(m)),money(cost(m))]));
else if(page==='members')content.innerHTML=table(['Mã hội viên','Họ tên','Số dư ví','Hạng'],[['HV001','Minh Anh',money(85000),'Thành viên'],['HV002','Hoàng Nam',money(120000),'Thành viên'],['HV003','Gia Huy',money(60000),'Thành viên']]);
else if(page==='services')content.innerHTML=table(['Mã','Dịch vụ','Đơn giá','Tồn kho'],[['DV001','Nước suối',money(10000),'24'],['DV002','Trà đào',money(15000),'18'],['DV003','Mì trứng',money(25000),'12']]);
else if(page==='bills')content.innerHTML=bills.length?table(['Hóa đơn','Máy / Gói','Tiền giờ / Gói','Dịch vụ','Tổng','Trạng thái'],bills.map((b,i)=>['HD'+String(i+1).padStart(3,'0'),b.id,money(b.hours),money(b.service),money(b.hours+b.service),'Đã thanh toán'])):'<div class="cn-detail"><h3>Chưa có hóa đơn trong bản mẫu</h3><div class="cn-sub">Chọn một máy đang sử dụng tại Phòng máy, rồi bấm “Thanh toán phiên”.</div></div>';
else content.innerHTML='<div class="cn-stats"><div class="cn-stat"><span class="cn-sub">Đã thu trong bản mẫu</span><strong>'+money(bills.reduce((a,b)=>a+b.hours+b.service,0))+'</strong></div><div class="cn-stat"><span class="cn-sub">Hóa đơn đã thanh toán</span><strong>'+bills.length+'</strong></div><div class="cn-stat"><span class="cn-sub">Tỷ lệ sử dụng máy</span><strong>'+Math.round(machines.filter(m=>m.state==='busy').length/12*100)+'%</strong></div></div>'+table(['Khu vực','Số máy','Đang sử dụng','Đơn giá / giờ'],['Thường','VIP'].map(z=>[z,machines.filter(m=>m.zone===z).length,machines.filter(m=>m.zone===z&&m.state==='busy').length,money(z==='VIP'?15000:10000)]));icons();}
function grid(){const list=machines.map((m,i)=>({m,i})).filter(({m})=>(filter==='all'||m.state===filter)&&(zone==='all'||m.zone===zone)&&m.id.toLowerCase().includes(query.toLowerCase()));root.querySelector('#cn-grid').innerHTML=list.length?list.map(({m,i})=>'<button class="cn-machine" data-machine="'+i+'" aria-pressed="'+(selected===i)+'"><i data-lucide="monitor" aria-hidden="true"></i><strong>'+m.id+' <span class="cn-sub">· '+m.zone+'</span></strong>'+badge(m)+'<span class="cn-sub">'+(m.state==='busy'?m.minutes+' phút · '+money(cost(m)):money(price(m))+' / giờ')+'</span></button>').join(''):'<div class="cn-empty">Không tìm thấy máy phù hợp.</div>';root.querySelectorAll('[data-machine]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.machine);grid();detail();feedback.textContent=''});icons();}
function detail(){const m=machines[selected];root.querySelector('#cn-detail').innerHTML='<h3>'+m.id+' · Khu '+m.zone+'</h3>'+badge(m)+'<dl><div><dt>Đơn giá</dt><dd>'+money(price(m))+'/giờ</dd></div>'+(m.state==='busy'?'<div><dt>Khách hàng</dt><dd>'+m.name+'</dd></div><div><dt>Thời gian</dt><dd>'+m.minutes+' phút</dd></div><div><dt>Tiền giờ</dt><dd>'+money(cost(m))+'</dd></div><div><dt>Dịch vụ</dt><dd>'+money(m.service)+'</dd></div>':'')+'</dl>'+(m.state==='busy'?'<div class="cn-total"><span>Tạm tính</span><strong>'+money(cost(m)+m.service)+'</strong></div><button class="cn-button" id="cn-order">Thêm trà đào · 15.000 đ</button><button class="cn-button cn-primary" id="cn-pay">Thanh toán phiên</button>':m.state==='free'?'<button class="cn-button cn-primary" id="cn-start">Mở phiên khách lẻ</button>':'<div class="cn-sub">Máy đang được kiểm tra thiết bị.</div><button class="cn-button" id="cn-ready">Hoàn tất bảo trì</button>');const bind=(id,fn)=>{const el=root.querySelector(id);if(el)el.onclick=fn};bind('#cn-order',()=>{m.service+=15000;saveDemo();detail();feedback.textContent='Đã thêm 1 trà đào vào '+m.id+' trong bản mẫu.'});bind('#cn-pay',()=>{bills.push({id:m.id,hours:cost(m),service:m.service});m.state='free';m.service=0;saveDemo();render();feedback.textContent='Đã thanh toán thử và đóng phiên '+m.id+'. Xem kết quả tại Hóa đơn.'});bind('#cn-start',()=>{m.state='busy';m.name='Khách lẻ';m.minutes=0;m.service=0;saveDemo();render();feedback.textContent='Đã mở phiên thử cho '+m.id+'.'});bind('#cn-ready',()=>{m.state='free';saveDemo();render();feedback.textContent=m.id+' đã sẵn sàng trong bản mẫu.'});}
const packs=[{name:'STANDARD 3H',zone:'Thường',hours:3,price:25000,gift:'Không kèm dịch vụ'},{name:'VIP 3H',zone:'VIP',hours:3,price:40000,gift:'1 nước suối'},{name:'VIP 5H',zone:'VIP',hours:5,price:65000,gift:'1 trà đào'}];let packFilter='all';
function renderCombos(){content.innerHTML='<div class="cn-banner"><div><div class="cn-kicker">CYBERNET / COMBO</div><h3>Chọn gói giờ phù hợp</h3><p>Gói giờ linh hoạt · Dịch vụ đi kèm · Giá rõ ràng</p></div><i data-lucide="ticket" aria-hidden="true"></i></div><div class="cn-toolbar" id="cn-pack-filters">'+[['all','Tất cả'],['Thường','Máy thường'],['VIP','Máy VIP']].map(([v,t])=>'<button class="cn-button cn-chip" data-pack-filter="'+v+'" aria-pressed="'+(packFilter===v)+'">'+t+'</button>').join('')+'</div><div class="cn-combos">'+packs.map((p,i)=>({p,i})).filter(({p})=>packFilter==='all'||p.zone===packFilter).map(({p,i})=>'<section class="cn-combo"><span class="cn-badge">MÁY '+p.zone.toUpperCase()+'</span><h3>'+p.name+'</h3><p>'+p.hours+' giờ sử dụng</p><p>Kích hoạt khi xác nhận mua</p><p>Tặng kèm: '+p.gift+'</p><div class="cn-combo-bottom"><strong>'+money(p.price)+'</strong><button class="cn-button cn-primary" data-buy="'+i+'">Mua gói</button></div></section>').join('')+'</div>';root.querySelectorAll('[data-pack-filter]').forEach(b=>b.onclick=()=>{packFilter=b.dataset.packFilter;renderCombos()});root.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>purchase(Number(b.dataset.buy)));icons();}
function purchase(i){const p=packs[i],d=root.querySelector('#cn-purchase');root.querySelector('#cn-purchase-body').innerHTML='<dl><div><dt>Tên gói</dt><dd>'+p.name+'</dd></div><div><dt>Loại máy</dt><dd>'+p.zone+'</dd></div><div><dt>Số giờ</dt><dd>'+p.hours+' giờ</dd></div><div><dt>Kích hoạt</dt><dd>Ngay sau khi mua</dd></div><div><dt>Giá</dt><dd>'+money(p.price)+'</dd></div><div><dt>Tặng kèm</dt><dd>'+p.gift+'</dd></div></dl><div class="cn-warning">Lưu ý: Gói chỉ áp dụng cho máy '+p.zone+'. Thời lượng được tính liên tục kể từ khi kích hoạt.</div><label class="cn-check"><input type="checkbox" id="cn-consent">Xác nhận tiếp tục mua gói</label><div class="cn-payment">◉ Tiền mặt</div><button id="cn-confirm" class="cn-button cn-primary cn-confirm" disabled>Xác nhận mua thử</button>';root.querySelector('#cn-consent').onchange=e=>root.querySelector('#cn-confirm').disabled=!e.target.checked;root.querySelector('#cn-confirm').onclick=()=>{bills.push({id:p.name,hours:p.price,service:0});saveDemo();d.close();feedback.textContent='Đã mua thử gói '+p.name+' — '+money(p.price)+'. Không phát sinh giao dịch thật.'};d.showModal();}root.querySelector('#cn-close').onclick=()=>root.querySelector('#cn-purchase').close();
root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;root.querySelectorAll('[data-page]').forEach(n=>n.removeAttribute('aria-current'));b.setAttribute('aria-current','page');root.querySelector('#cn-title').textContent=b.textContent.trim();render()});root.querySelector('[data-page=machines]').click();})();
